# Generated by Django 5.2.6 on 2025-09-19 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.PositiveIntegerField(help_text='Class/Grade level (1-10)', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['class_number'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organization', models.BooleanField(default=False, help_text='Set to True if contact is an organization, False if it is a person')),
                ('email', models.EmailField(blank=True, help_text='Email address (RFC 5321 max length 254 characters', max_length=254)),
                ('phone_country_code', models.CharField(default='977', help_text='Country calling code digits (i.e. 977 for Nepal)', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$', 'Enter 1-4 digits for country code')])),
                ('phone_number', models.CharField(help_text='Local phone number without country code', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{3,15}$', 'Enter a valid phone number (3-15 digits)')])),
                ('address', models.TextField(help_text='Postal address')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of emergency contact person', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number without country code', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{3,15}$', 'Enter a valid phone number (3-15 digits)')])),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='Relationship of the emergency contact', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization Type: School, College, NGO, FPL', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Organization Type',
                'verbose_name_plural': 'Organization Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Palika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palika', models.CharField(help_text='e.g., Lalitpur', max_length=100, unique=True, verbose_name='Palika')),
                ('short_name', models.CharField(help_text='e.g., LTT', max_length=6, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Palika',
                'verbose_name_plural': 'Palikas',
                'ordering': ['palika'],
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='School type: Private, Public, Community', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'School Type',
                'verbose_name_plural': 'School Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Weekdays',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
            ],
            options={
                'verbose_name': 'Organization Contact',
                'verbose_name_plural': 'Organization Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contact',),
        ),
        migrations.CreateModel(
            name='PersonContact',
            fields=[
            ],
            options={
                'verbose_name': 'Person Contact',
                'verbose_name_plural': 'Person Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contact',),
        ),
    ]
