# Generated by Django 5.2.6 on 2025-09-15 09:52
#
# # Generated by Django X.X on YYYY-MM-DD HH:MM

from django.db import migrations


def create_core_data(apps, schema_editor):
    """
    Forward migration: Create initial core data
    """
    # Get model references
    Palika = apps.get_model("core", "Palika")
    OrganizationType = apps.get_model("core", "OrganizationType")
    SchoolType = apps.get_model("core", "SchoolType")
    Class = apps.get_model("core", "Class")
    Weekday = apps.get_model("core", "Weekday")

    # Create Palikas (replace with your actual data)
    palikas_data = [
        ("Lalitpur", "ltt"),
        ("Swoyambhu", "somu"),
        ("Hetauda", "htd"),
        ("Chabahil", "chbl"),
        ("Kalanki-Kirtipur", "kilkir"),
        ("Basantapur", "bsnt"),
        ("Koteshwor-Baneshwor", "kotban"),
        ("Bhaktapur", "bhkt"),
        ("Chapagaun", "cpg"),
        # Add more palikas as needed
    ]

    for palika_name, short_name in palikas_data:
        Palika.objects.get_or_create(palika=palika_name, short_name=short_name)

    # Create Organization Types
    org_types = ["School", "College", "NGO", "FPL"]
    for org_type in org_types:
        OrganizationType.objects.get_or_create(name=org_type)

    # Create School Types
    school_types = ["Private", "Public", "Community"]
    for school_type in school_types:
        SchoolType.objects.get_or_create(name=school_type)

    # Create Classes (1-10)
    for class_num in range(1, 11):
        Class.objects.get_or_create(class_number=class_num)

    # Create Weekdays
    weekdays = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
    ]
    for weekday in weekdays:
        Weekday.objects.get_or_create(name=weekday)


def reverse_core_data(apps, schema_editor):
    """
    Reverse migration: Remove core data
    """
    # Get model references
    Palika = apps.get_model("core", "Palika")
    OrganizationType = apps.get_model("core", "OrganizationType")
    SchoolType = apps.get_model("core", "SchoolType")
    Class = apps.get_model("core", "Class")
    Weekday = apps.get_model("core", "Weekday")

    # Delete all core data (be careful with this!)
    Palika.objects.all().delete()
    OrganizationType.objects.all().delete()
    SchoolType.objects.all().delete()
    Class.objects.all().delete()
    Weekday.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_core_data,
            reverse_core_data,
        ),
    ]
