# Generated by Django 5.2.6 on 2025-10-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_taxonomy_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationContact',
        ),
        migrations.DeleteModel(
            name='PersonContact',
        ),
    ]
