# Generated by Django 5.2.6 on 2025-09-18 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_taxonomy_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organization', models.BooleanField(default=False, help_text='Set to True if contact is an organization, False if it is a person')),
                ('email', models.EmailField(blank=True, help_text='Email address (RFC 5321 max length 254 characters', max_length=254)),
                ('phone_country_code', models.CharField(default='977', help_text='Country calling code digits (i.e. 977 for Nepal)', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$', 'Enter 1-4 digits for country code')])),
                ('phone_number', models.CharField(help_text='Local phone number without country code', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{3,15}$', 'Enter a valid phone number (3-15 digits)')])),
                ('address', models.TextField(help_text='Postal address')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of emergency contact person', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number without country code', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{3,15}$', 'Enter a valid phone number (3-15 digits)')])),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='Relationship of the emergency contact', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
