# Generated by Django 5.2.6 on 2025-09-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
            ],
            options={
                'verbose_name': 'Organization Contact',
                'verbose_name_plural': 'Organization Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contact',),
        ),
        migrations.CreateModel(
            name='PersonContact',
            fields=[
            ],
            options={
                'verbose_name': 'Person Contact',
                'verbose_name_plural': 'Person Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contact',),
        ),
    ]
