# Generated by Django 5.2.6 on 2025-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100, unique=True, verbose_name='Game Name')),
                ('description', models.TextField(blank=True, verbose_name='Game Description')),
                ('how_to', models.TextField(blank=True, verbose_name='How to Play')),
                ('team_prep', models.TextField(blank=True, verbose_name='Team Preparation')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('image_url', models.URLField(blank=True, verbose_name='Image URL')),
                ('challenges', models.JSONField(blank=True, default=dict, verbose_name='Challenges')),
                ('questions', models.JSONField(blank=True, default=dict, verbose_name='Questions')),
                ('quality_checklist', models.JSONField(blank=True, default=dict, verbose_name='Quality Checklist')),
                ('materials_required', models.JSONField(blank=True, default=dict, verbose_name='Materials Required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['game'],
            },
        ),
    ]
