# Generated by Django 5.2.6 on 2025-09-18 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Game Name')),
                ('description', models.TextField(blank=True, verbose_name='Game Description')),
                ('how_to', models.TextField(blank=True, verbose_name='How to Play')),
                ('team_prep', models.TextField(blank=True, verbose_name='Team Preparation')),
                ('challenges', models.TextField(blank=True, verbose_name='Challenges')),
                ('questions', models.TextField(blank=True, verbose_name='Questions')),
                ('quality_checklist', models.TextField(blank=True, verbose_name='Quality Checklist')),
                ('materials', models.TextField(blank=True, verbose_name='Materials Required')),
                ('video_url', models.URLField(blank=True, unique=True, validators=[django.core.validators.URLValidator()], verbose_name='Video URL')),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the game', null=True, upload_to='games/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
    ]
