# Generated by Django 5.2.6 on 2025-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.PositiveIntegerField(help_text='Class/Grade level (1-10)', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['class_number'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization Type: School, College, NGO, FPL', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Organization Type',
                'verbose_name_plural': 'Organization Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Palika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palika', models.CharField(help_text='e.g., Latipur', max_length=100, unique=True, verbose_name='Palika')),
                ('short_name', models.CharField(help_text='e.g., LTT', max_length=6, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Palika',
                'verbose_name_plural': 'Palikas',
                'ordering': ['palika'],
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='School type: Private, Public, Community', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'School Type',
                'verbose_name_plural': 'School Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Weekdays',
                'ordering': ['pk'],
            },
        ),
    ]
