# Generated by Django 5.2.6 on 2025-10-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_organizationcontact_delete_personcontact'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonContact',
            fields=[
            ],
            options={
                'verbose_name': 'Person Contact',
                'verbose_name_plural': 'Person Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contact',),
        ),
        migrations.AlterModelOptions(
            name='fplmember',
            options={'permissions': [('view_own_palika_members', 'Can view members from own palika'), ('add_own_palika_members', 'Can add members to own palika'), ('change_own_palika_members', 'Can change members from own palika'), ('delete_own_palika_members', 'Can delete members from own palika')], 'verbose_name': 'FPL Member', 'verbose_name_plural': 'FPL Members'},
        ),
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.personcontact'),
        ),
    ]
