# Generated by Django 5.2.6 on 2025-09-19 10:11
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_taxonomy_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the organization', max_length=255)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude coordinate', null=True)),
                ('general_location', models.CharField(blank=True, help_text='Landmark or general location description', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Whether this organization is currently active')),
                ('contact', models.OneToOneField(help_text='Contact information for this organization', on_delete=django.db.models.deletion.CASCADE, to='core.organizationcontact')),
                ('org_type', models.ForeignKey(help_text='Type of organization (School, College, NGO, FPL)', on_delete=django.db.models.deletion.PROTECT, to='core.organizationtype')),
                ('palika', models.ForeignKey(blank=True, help_text='Administrative division where organization is located', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.palika')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_1_fee', models.IntegerField(blank=True, help_text='Fee for class 1', null=True)),
                ('provides_food', models.BooleanField(help_text='Whether the school provides food')),
                ('first_session_date', models.DateField(help_text='Date of the first session')),
                ('start_time_firsthalf', models.TimeField(help_text='Start time for the first half of the day')),
                ('start_time_secondhalf', models.TimeField(help_text='Start time for the second half of the day')),
                ('session_duration', models.IntegerField(help_text='Duration of each session in minutes')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_school', to='organizations.organization')),
                ('school_type', models.ForeignKey(help_text='Type of school (e.g., Private, Government, Community)', on_delete=django.db.models.deletion.PROTECT, to='core.schooltype')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['organization'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the role (e.g., Teacher, Student, Staff)', max_length=100)),
                ('organization', models.ForeignKey(help_text='Organization this role is associated with', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'organization'), name='unique_role_per_organization')],
            },
        ),
        migrations.CreateModel(
            name='Schoolclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.IntegerField(help_text='Maximum number of students in the class')),
                ('Class', models.ForeignKey(help_text='Class/Grade level', on_delete=django.db.models.deletion.PROTECT, to='core.class')),
                ('school', models.ForeignKey(help_text='School this class is associated with', on_delete=django.db.models.deletion.PROTECT, to='organizations.school')),
            ],
            options={
                'verbose_name': 'School Class',
                'verbose_name_plural': 'School Classes',
                'ordering': ['school'],
                'constraints': [models.UniqueConstraint(fields=('Class', 'school'), name='unique_class_per_school')],
            },
        ),
    ]
