# Generated by Django 5.2.6 on 2025-10-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_organizationcontact_delete_personcontact'),
        ('organizations', '0002_seed_funplaylearn'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
            ],
            options={
                'verbose_name': 'Organization Contact',
                'verbose_name_plural': 'Organization Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contact',),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact',
            field=models.OneToOneField(help_text='Contact information for this organization', on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationcontact'),
        ),
    ]
